import type { Metadata } from "next";
import "@/assets/styles/globals.css";
import AppProviders from "@/providers/AppProviders";
import Header from "@/common/Header";
import { Box, CssBaseline } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  sidebar,
}: Readonly<{
  children: React.ReactNode;
  sidebar: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id="app">
        <AppProviders>
          <Box sx={{ display: "flex" }}>
            <CssBaseline />
            {/* <Header /> */}
            {sidebar}
            <Box
              component="main"
              sx={{
                flexGrow: 1,
                bgcolor: "background.default",
                height: "100vh",
              }}
            >
              {children}
            </Box>
          </Box>
        </AppProviders>
      </body>
    </html>
  );
}
